//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrumMachine
{
    using System;
    using System.Collections.Generic;
    
    public partial class instrument
    {
        public int id { get; set; }
        public Nullable<int> machineID { get; set; }
        public string audiofile { get; set; }
        public string sequence { get; set; }
    
        public virtual machine machine { get; set; }
        public virtual sound sound { get; set; }
    }
}
