//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrumMachine
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public machine()
        {
            this.instruments = new HashSet<instrument>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> gridLength { get; set; }
        public Nullable<int> tempo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instrument> instruments { get; set; }
    }
}
